version: '3.8'

services:
   php:
     build: .
     environment:
      - CODFLIX_DB_HOST=db
      - CODFLIX_DB_NAME=codflix
      - CODFLIX_DB_USER=codflix
      - CODFLIX_DB_PASSWORD=codflix
     volumes:
       - .:/var/www/html/
     ports:
       - 8080:80
   db:
     command: --default-authentication-plugin=mysql_native_password
     image: mysql:8.0
     volumes:
       - ./codflix.sql:/docker-entrypoint-initdb.d/1.sql
       - dbdata:/var/lib/mysql
     ports:
      - 3307:3306
     environment:
       MYSQL_ROOT_PASSWORD: codflix
       MYSQL_DATABASE: codflix
       MYSQL_USER: codflix
       MYSQL_PASSWORD: codflix
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - '9090:80'
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: codflix

volumes:
  dbdata: {}
